spring:
  redis:
    host: 192.168.222.128
  rabbitmq:
    host: 192.168.222.128
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
  application:
    name: sms-server
server:
  port: 8085


